export * as authService from './auth.js'
export * as avatarService from './avatar.js'
export * as bannerService from './banner.js'
export * as friendService from './friend.js'
export * as postService from './post.js'
export * as userService from './user.js'
